routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/hubungi', 'HomeController@showContactUs');
Route::post('/hubungi', 'HomeController@kirimPesan')->name('home.kirimPesan');

Route::get('/bukutamu/pengunjung', 'Frontend\PengunjungController@index')->name('home.pengunjung');
Route::post('/bukutamu/pengunjung/store', 'Frontend\PengunjungController@store')->name('home.pengunjung.store');
Route::get('/bukutamu/perjanjian', 'Frontend\PerjanjianController@index')->name('home.perjanjian');
Route::post('/bukutamu/perjanjian/store', 'Frontend\PerjanjianController@store')->name('home.perjanjian.store');

Route::get('/p/{slug}', 'HomeController@showPage')->name('home.showPage');

Route::get('/berita', 'HomeController@listPost')->name('home.listPost');
Route::get('/berita/{id}-{post}', 'HomeController@showPost')->name('home.showPost');

Route::get('/tag/{slug}', 'HomeController@showTags')->name('home.showTags');
Route::get('/topik/{slug}', 'HomeController@showCategories')->name('home.showCategories');

Route::get('/agenda', 'HomeController@listAgenda')->name('home.listAgenda');
Route::get('/agenda/{id}/{slug}', 'HomeController@showAgenda')->name('home.showAgenda');

Route::get('/pengumuman', 'HomeController@listPengumuman')->name('home.listPengumuman');
Route::get('/pengumuman/{id}/{slug}', 'HomeController@showPengumuman')->name('home.showPengumuman');

Route::get('/galeri', 'HomeController@listGallery')->name('home.listGallery');
Route::get('/galeri/{id}', 'HomeController@showGallery')->name('home.showGallery');

Route::get('/search', 'HomeController@showSearch');

Route::get('/faq', 'HomeController@listFaq')->name('home.listFaq');
Route::get('/layanan', 'HomeController@listLayanan')->name('home.listLayanan');


Auth::routes();
Route::group(['prefix' => 'panelroom'], function () {
    Route::get('/','DashboardController@index');
    Route::post('berita/addTags', 'BeritaController@addTags')->name('berita.addTags');

    Route::post('quickdraft', 'BeritaController@quickDraft')->name('berita.quickDraft');
    
    Route::resource('berita', 'BeritaController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('tag', 'TagController');
    Route::resource('halaman', 'HalamanController');
    
    Route::get('media/modal', 'MediaController@modalshow')->name('media.modal');
    Route::get('media/modal-gallery', 'MediaController@modalShowGallery')->name('media.modal_gallery');
    Route::match(['post', 'patch'], 'media/ajaxstore', 'MediaController@ajaxStore')->name('media.ajaxstore');
    Route::resource('media', 'MediaController');
    
    Route::get('pdf/modal', 'PdfController@modalshow')->name('pdf.modal');
    Route::post('pdf/ajaxstore', 'PdfController@ajaxStore')->name('pdf.ajaxstore');
    Route::resource('pdf', 'PdfController');

    Route::resource('menu', 'LayoutController');

    Route::post('dmenu/reorder', 'MenuController@reOrder')->name('dmenu.reorder');
    Route::resource('dmenu', 'MenuController');

    Route::get('agenda/getAgenda', 'AgendaController@getAgenda');
    Route::resource('agenda', 'AgendaController');

    Route::resource('slider', 'SliderController');
    Route::resource('users', 'UsersController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('pesan', 'PesanController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('iklan', 'IklanController');
    Route::resource('faq', 'Admin\FaqController');
    Route::delete('setting/deleted', 'SettingController@deleted')->name('setting.deleted');
    Route::resource('setting', 'SettingController');
    Route::resource('layanan', 'Admin\LayananController');
    Route::resource('linkterkait', 'Admin\LinkterkaitController');
    Route::resource('dataindek', 'Admin\DataindekController');
    Route::get('pengunjung/pdf', 'Admin\PengunjungController@pdf')->name('pengunjung.pdf');
    Route::get('pengunjung/excel', 'Admin\PengunjungController@excel')->name('pengunjung.excel');
    Route::resource('pengunjung', 'Admin\PengunjungController');
    Route::get('perjanjian/excel', 'Admin\PerjanjianController@excel')->name('perjanjian.excel');
    Route::get('perjanjian/pdf', 'Admin\PerjanjianController@pdf')->name('perjanjian.pdf');
    Route::resource('perjanjian', 'Admin\PerjanjianController');
    
});
Route::get('/panelroom', 'DashboardController@index')->name('dashboard');

// Route::get('/home', 'HomeController@index')->name('home');

app/Models/LinkTerkait.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LinkTerkait extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $appends = ['media_path'];

    public function Image()
    {
        return $this->belongsTo(Media::class,'id_media');
    }

    public function media(){
        return $this->belongsTo(Media::class,'id_media','id');
    }


    public function getMediaPathAttribute()
    {
        return asset("/files/" . $this->Image->path);
    }
}

app/Http/Controllers/Admin/LinkterkaitController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\LinkTerkait;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
class LinkterkaitController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

     
    public function index()
    {
        $getModul = LinkTerkait::paginate(10)->onEachSide(2);
        return view('panel.link_terkait.index',['data'=>$getModul]);
    }

   
    public function create()
    {
        return view('panel.link_terkait.create');
    }

    public function store(Request $request)
    {
        $data = $request->except('_token');
        LinkTerkait::create($data);
        return redirect()->route('linkterkait.index')->with('message', 'Link Terkait telah ditambah');
    }

    public function edit($id)
    {
        $getModul = LinkTerkait::find($id);
        return view('panel.link_terkait.edit',['data'=>$getModul]);
    }

    public function update(Request $request,$id)
    {
        $data = $request->except('_token','_method');
        LinkTerkait::where('id',$id)->update($data);
        return redirect()->route('linkterkait.index')->with('message', 'Link Terkait telah diupdate');
    }

    public function destroy($id)
    {
        $modul = LinkTerkait::find($id);
        if ($modul->delete()) {
            return redirect()->back()->with('message', 'Link Terkait telah dihapus');
        }
    }
}

resources/views/panel/link_terkait/create.blade.php
@extends('panel.layouts.apps')
@include('panel.link_terkait.submenu')
@section('content')
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload.css") !!}>
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload-ui.css") !!}>
@if ($errors->any())
<div class="alert alert-danger">
    @foreach ($errors->all() as $error)
    <ul>
        <li>{{ $error }}</li>
    </ul>
    @endforeach
</div>
@endif
<form class="kt-form kt-form--label-right row" id="f_linkterkait" action="{{ route('linkterkait.store') }}" method="POST"
    enctype="multipart/form-data">
    {{csrf_field()}}
    <div class="col-8">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body">
                <div class="form-group form-group-last">
                    <div class="alert alert-secondary" role="alert">
                        <div class="alert-icon"><i class="flaticon-add kt-font-brand"></i></div>
                        <div class="alert-text">
                            Tambah Link Terkait
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Judul Link Terkait *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="" id="nama" name="nama"
                            placeholder="Judul Link Terkait">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Tautan</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="" id="link" name="link" placeholder="Tautan">
                    </div>
                </div>

                
            </div>

            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button class="btn btn-success" type="submit">Submit</button>
                            <button type="reset" class="btn btn-secondary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Media
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="form-group row">
                    <input type="hidden" id="imageIdnews" value="" name="id_media">
                    <div class="col-12">
                        <div class="preview-pic"></div>
                        <hr />
                    </div>
                    <div class="col-6 text-center">
                        <span class="btn btn-success fileinput-button col-12">
                            <span class="uploadnew ">Upload</span>
                            <span class="changeupload d-none">Ganti</span>
                            <input id="fileupload" type="file" name="files">
                        </span>
                    </div>
                    <div class="col-6 text-center">
                        <a href="#" class="btn btn-primary fileinput-button pilihgambar col-12">
                            Pilih
                        </a>
                        <a href="#" class="btn btn-danger fileinput-button hapusgambar d-none col-12">
                            Hapus
                        </a>
                    </div>
                </div>
                {{-- <div class="form-group">
                    <textarea class="form-control" name="ket_gambar" id="ket_gambar" cols="30" rows="3" placeholder="Keterangan Gambar"></textarea>
                </div> --}}
            </div>
        </div>
   
    </div>
</form>
@endsection
@push('script')
<script src="{!! asset("/js/jquery-ui.js") !!}"></script>
<script src="{!! asset("/js/jquery.fileupload.js") !!}"></script>

<script>
    $(document).on('change', '#position', function(e) {
        let posVal = $('#position').val();
        switch (posVal) {
            case "1":
                $('.ordering').addClass('d-none');
                break;
            case "2":
                $('.ordering').addClass('d-none');
                break;
            default:
                $('.ordering').removeClass('d-none');
                break;
        }
    });
    $(document).ready(function() {
        $("#f_iklan").validate({
            rules: {
                title: {
                    required: !0
                },
                position: {
                    required: !0
                }
            },
            errorPlacement: function(e, r) {
                var i = r.closest(".input-group");
                i.length ? i.after(e.addClass("invalid-feedback")) : r.after(e.addClass(
                    "invalid-feedback"))
            },
            invalidHandler: function(e, r) {
                KTUtil.scrollTop();
            }
        });
    });
    $(function() {
        $('#fileupload').fileupload({
            url: '{!! route("media.ajaxstore") !!}',
            dataType: 'json',
            done: function(e, data) {
                var dataRes = data.result;
                if (dataRes.status == 1) {
                    $('.uploadnew').addClass('d-none');
                    $('.changeupload').removeClass('d-none');
                    $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + dataRes
                        .path + '" />');
                    $('fileinput-button').html('Ganti Gambar');
                    $('#imageIdnews').val(dataRes.imageId);
                    $('.pilihgambar').addClass('d-none');
                    $('.hapusgambar').removeClass('d-none');
                    toastr.success(dataRes.message, "Success");
                } else {
                    toastr.error(dataRes.message, "Failed");
                }
            }
        });
    });
    $(document).on('click', '.pilihgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        $modal.find(".modal-title").html("Pilih Gambar");
        $modal.find(".modal-body").html("");
        $.ajax({
            url: "{{ route('media.modal') }}",
            type: "GET",
            data: {},
            success: function(e) {
                $modal.find(".modal-body").html(e);
            }
        });
        $modal.find(".modal-footer").html('');
        $modal.modal('show');
    });
    $(document).on('click', '.choosepicture', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        var id_gambar = $(this).attr('id-gambar');
        var path_gambar = $(this).attr('path-gambar');
        $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + path_gambar + '" />');
        $('#imageIdnews').val(id_gambar);
        $('.pilihgambar').addClass('d-none');
        $('.hapusgambar').removeClass('d-none');
        $modal.modal('hide');
    });
    $(document).on('click', '.hapusgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        $('.preview-pic').html('');
        $('#imageIdnews').val('');
        $('.pilihgambar').removeClass('d-none');
        $('.hapusgambar').addClass('d-none');
        $('.uploadnew').removeClass('d-none');
        $('.changeupload').addClass('d-none');
    });
</script>
@endpush

resources/views/panel/link_terkait/edit.blade.php
@extends('panel.layouts.apps')
@include('panel.link_terkait.submenu')
@section('content')
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload.css") !!}>
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload-ui.css") !!}>
@if ($errors->any())
<div class="alert alert-danger">
    @foreach ($errors->all() as $error)
    <ul>
        <li>{{ $error }}</li>
    </ul>
    @endforeach
</div>
@endif
<form class="kt-form kt-form--label-right row" id="f_linkterkait" action="{{ route('linkterkait.update',$data->id) }}" method="POST"
    enctype="multipart/form-data">
    {{csrf_field()}}
    @method('patch')
    <div class="col-8">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body">
                <div class="form-group form-group-last">
                    <div class="alert alert-secondary" role="alert">
                        <div class="alert-icon"><i class="flaticon-add kt-font-brand"></i></div>
                        <div class="alert-text">
                            Edit Link Terkait
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Judul Link Terkait *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="{{ $data->nama }}" id="nama" name="nama"
                            placeholder="Judul Link Terkait">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Tautan</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="{{ $data->link }}" id="link" name="link" placeholder="Tautan">
                    </div>
                </div>

                
            </div>

            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button class="btn btn-success" type="submit">Submit</button>
                            <button type="reset" class="btn btn-secondary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Media
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="form-group row">
                    <input type="hidden" id="imageIdnews" value="" name="id_media">
                    <div class="col-12">
                        <div class="preview-pic">
                            @if (!empty($data->id_media))
                            @if (!empty($data->media->path))
                                <img src="{{ asset("files/".$data->media->path_220) }}" alt="" width="100%">
                            @else
                                Photo Telah Dihapus
                            @endif
                        @endif
                        </div>
                        <hr />
                    </div>
                    <div class="col-6 text-center">
                        <span class="btn btn-success fileinput-button col-12">
                            <span class="uploadnew ">Upload</span>
                            <span class="changeupload d-none">Ganti</span>
                            <input id="fileupload" type="file" name="files">
                        </span>
                    </div>
                    <div class="col-6 text-center">
                        <a href="#" class="btn btn-primary fileinput-button pilihgambar col-12">
                            Pilih
                        </a>
                        <a href="#" class="btn btn-danger fileinput-button hapusgambar d-none col-12">
                            Hapus
                        </a>
                    </div>
                </div>
                {{-- <div class="form-group">
                    <textarea class="form-control" name="ket_gambar" id="ket_gambar" cols="30" rows="3" placeholder="Keterangan Gambar"></textarea>
                </div> --}}
            </div>
        </div>
   
    </div>
</form>
@endsection
@push('script')
<script src="{!! asset("/js/jquery-ui.js") !!}"></script>
<script src="{!! asset("/js/jquery.fileupload.js") !!}"></script>

<script>
    $(document).on('change', '#position', function(e) {
        let posVal = $('#position').val();
        switch (posVal) {
            case "1":
                $('.ordering').addClass('d-none');
                break;
            case "2":
                $('.ordering').addClass('d-none');
                break;
            default:
                $('.ordering').removeClass('d-none');
                break;
        }
    });
    $(document).ready(function() {
        $("#f_iklan").validate({
            rules: {
                title: {
                    required: !0
                },
                position: {
                    required: !0
                }
            },
            errorPlacement: function(e, r) {
                var i = r.closest(".input-group");
                i.length ? i.after(e.addClass("invalid-feedback")) : r.after(e.addClass(
                    "invalid-feedback"))
            },
            invalidHandler: function(e, r) {
                KTUtil.scrollTop();
            }
        });
    });
    $(function() {
        $('#fileupload').fileupload({
            url: '{!! route("media.ajaxstore") !!}',
            dataType: 'json',
            done: function(e, data) {
                var dataRes = data.result;
                if (dataRes.status == 1) {
                    $('.uploadnew').addClass('d-none');
                    $('.changeupload').removeClass('d-none');
                    $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + dataRes
                        .path + '" />');
                    $('fileinput-button').html('Ganti Gambar');
                    $('#imageIdnews').val(dataRes.imageId);
                    $('.pilihgambar').addClass('d-none');
                    $('.hapusgambar').removeClass('d-none');
                    toastr.success(dataRes.message, "Success");
                } else {
                    toastr.error(dataRes.message, "Failed");
                }
            }
        });
    });
    $(document).on('click', '.pilihgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        $modal.find(".modal-title").html("Pilih Gambar");
        $modal.find(".modal-body").html("");
        $.ajax({
            url: "{{ route('media.modal') }}",
            type: "GET",
            data: {},
            success: function(e) {
                $modal.find(".modal-body").html(e);
            }
        });
        $modal.find(".modal-footer").html('');
        $modal.modal('show');
    });
    $(document).on('click', '.choosepicture', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        var id_gambar = $(this).attr('id-gambar');
        var path_gambar = $(this).attr('path-gambar');
        $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + path_gambar + '" />');
        $('#imageIdnews').val(id_gambar);
        $('.pilihgambar').addClass('d-none');
        $('.hapusgambar').removeClass('d-none');
        $modal.modal('hide');
    });
    $(document).on('click', '.hapusgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        $('.preview-pic').html('');
        $('#imageIdnews').val('');
        $('.pilihgambar').removeClass('d-none');
        $('.hapusgambar').addClass('d-none');
        $('.uploadnew').removeClass('d-none');
        $('.changeupload').addClass('d-none');
    });
</script>
@endpush

resources/views/panel/link_terkait/index.blade.php
@extends('panel.layouts.apps')
@include('panel.link_terkait.submenu')
@section('content')
@if(session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-menu-2"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                List Link Terkait
            </h3>
        </div>
    </div>
    <div class="kt-portlet__body">
        <table class="table table-striped" id="t_menu">
            <thead>
                <tr>
                    <th>Judul</th>
                    <th>Gambar</th>
                    <th>Tautan</th>
                    <th style="text-align:center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $item)
                <tr>
                    <td>{{ $item->nama }}</td>
                    <td><img src="{{ $item->media_path }}" alt="" width="200"></td>
                    <td>{{ $item->link }}</td>
                    <td width="20%" style="text-align:center">
                        <a class="btn btn-primary btn-icon" href="{{ route('linkterkait.edit',$item->id) }}"><i
                                class="fas fa-pencil-alt"></i></a>
                        <button type="button" class="btn btn-danger destroy deletelinkterkait btn-icon" id-linkterkait="{{ $item->id }}"><i
                                class="fas fa-trash"></i></button>
                        <form action="{{ route('linkterkait.destroy',$item->id) }}" style="display:none"
                            id="destroy_{{ $item->id }}" method="POST">
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>
        <div class="kt-pagination  kt-pagination--brand">
            {{ $data->links() }}
            <div class="kt-pagination__toolbar">
                <span class="pagination__desc">
                    Displaying {{ ($data->total() <= 10)?$data->total():($data->currentpage()-1)*$data->perpage()+1 }}
                    {{ ($data->currentpage()*$data->perpage() < 10)?"to ".$data->currentpage()*$data->perpage():""}} of
                    {{$data->total()}} records
                </span>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script>
    $(document).on('click', '.deletelinkterkait', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var valuelinkterkait = $(this).attr('id-linkterkait');
        $modal.find(".modal-title").html("Hapus Slide");
        $modal.find(".modal-body").html("Apakah Anda Yakin Ingin menghapus linkterkait ini?");
        $modal.find(".modal-footer").html(
            '<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button><button type="button" class="btn btn-primary yeshapulinkterkait" valueid="' +
            valuelinkterkait + '">OK</button>');
        $modal.modal('show');
    });
    $(document).on('click', '.yeshapulinkterkait', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var id_linkterkait = $(this).attr('valueid');
        $('#destroy_' + id_linkterkait).trigger('submit');
        $modal.modal('hide');
    });
</script>
@endpush

resources/views/panel/link_terkait/submenu.blade.php
@section('submenu')
<span class="kt-subheader__separator kt-hidden"></span>
<a href="{{ route('linkterkait.create') }}" class="btn btn-label-primary btn-bold btn-sm btn-icon-h kt-margin-l-10">
    <i class="fas fa-plus"></i> Tambah Link Terkait
</a>
@endsection