routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/hubungi', 'HomeController@showContactUs');
Route::post('/hubungi', 'HomeController@kirimPesan')->name('home.kirimPesan');

Route::get('/bukutamu/pengunjung', 'Frontend\PengunjungController@index')->name('home.pengunjung');
Route::post('/bukutamu/pengunjung/store', 'Frontend\PengunjungController@store')->name('home.pengunjung.store');
Route::get('/bukutamu/perjanjian', 'Frontend\PerjanjianController@index')->name('home.perjanjian');
Route::post('/bukutamu/perjanjian/store', 'Frontend\PerjanjianController@store')->name('home.perjanjian.store');

Route::get('/p/{slug}', 'HomeController@showPage')->name('home.showPage');

Route::get('/berita', 'HomeController@listPost')->name('home.listPost');
Route::get('/berita/{id}-{post}', 'HomeController@showPost')->name('home.showPost');

Route::get('/tag/{slug}', 'HomeController@showTags')->name('home.showTags');
Route::get('/topik/{slug}', 'HomeController@showCategories')->name('home.showCategories');

Route::get('/agenda', 'HomeController@listAgenda')->name('home.listAgenda');
Route::get('/agenda/{id}/{slug}', 'HomeController@showAgenda')->name('home.showAgenda');

Route::get('/pengumuman', 'HomeController@listPengumuman')->name('home.listPengumuman');
Route::get('/pengumuman/{id}/{slug}', 'HomeController@showPengumuman')->name('home.showPengumuman');

Route::get('/galeri', 'HomeController@listGallery')->name('home.listGallery');
Route::get('/galeri/{id}', 'HomeController@showGallery')->name('home.showGallery');

Route::get('/search', 'HomeController@showSearch');

Route::get('/faq', 'HomeController@listFaq')->name('home.listFaq');
Route::get('/layanan', 'HomeController@listLayanan')->name('home.listLayanan');


Auth::routes();
Route::group(['prefix' => 'panelroom'], function () {
    Route::get('/','DashboardController@index');
    Route::post('berita/addTags', 'BeritaController@addTags')->name('berita.addTags');

    Route::post('quickdraft', 'BeritaController@quickDraft')->name('berita.quickDraft');
    
    Route::resource('berita', 'BeritaController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('tag', 'TagController');
    Route::resource('halaman', 'HalamanController');
    
    Route::get('media/modal', 'MediaController@modalshow')->name('media.modal');
    Route::get('media/modal-gallery', 'MediaController@modalShowGallery')->name('media.modal_gallery');
    Route::match(['post', 'patch'], 'media/ajaxstore', 'MediaController@ajaxStore')->name('media.ajaxstore');
    Route::resource('media', 'MediaController');
    
    Route::get('pdf/modal', 'PdfController@modalshow')->name('pdf.modal');
    Route::post('pdf/ajaxstore', 'PdfController@ajaxStore')->name('pdf.ajaxstore');
    Route::resource('pdf', 'PdfController');

    Route::resource('menu', 'LayoutController');

    Route::post('dmenu/reorder', 'MenuController@reOrder')->name('dmenu.reorder');
    Route::resource('dmenu', 'MenuController');

    Route::get('agenda/getAgenda', 'AgendaController@getAgenda');
    Route::resource('agenda', 'AgendaController');

    Route::resource('slider', 'SliderController');
    Route::resource('users', 'UsersController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('pesan', 'PesanController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('iklan', 'IklanController');
    Route::resource('faq', 'Admin\FaqController');
    Route::delete('setting/deleted', 'SettingController@deleted')->name('setting.deleted');
    Route::resource('setting', 'SettingController');
    Route::resource('layanan', 'Admin\LayananController');
    Route::resource('linkterkait', 'Admin\LinkterkaitController');
    Route::resource('dataindek', 'Admin\DataindekController');
    Route::get('pengunjung/pdf', 'Admin\PengunjungController@pdf')->name('pengunjung.pdf');
    Route::get('pengunjung/excel', 'Admin\PengunjungController@excel')->name('pengunjung.excel');
    Route::resource('pengunjung', 'Admin\PengunjungController');
    Route::get('perjanjian/excel', 'Admin\PerjanjianController@excel')->name('perjanjian.excel');
    Route::get('perjanjian/pdf', 'Admin\PerjanjianController@pdf')->name('perjanjian.pdf');
    Route::resource('perjanjian', 'Admin\PerjanjianController');
    
});
Route::get('/panelroom', 'DashboardController@index')->name('dashboard');

// Route::get('/home', 'HomeController@index')->name('home');

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    protected $fillable = [
        'title', 
        'slug', 
        'order', 
        'parent_id',
        'layout_id'
    ];

}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use Illuminate\Http\Request;

class MenuController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(Request $request)
    {
        $modul = new Menu();
        $modul->title = $request->input('title');
        $modul->slug = $request->input('slug');
        $modul->order = Menu::where("layout_id", (int) $request->layout_id)->max('order') + 1;
        $modul->layout_id = (int)$request->layout_id;
        $returnData = array();
        if ($modul->save()) {
            $returnData['status'] = 1;
            $returnData['message'] = "Sukses Menambah Menu";
            $returnData['menuId'] = $modul->id;
            $returnData['menuTitle'] = $modul->title;
            $returnData['menuSlug'] = $modul->slug;
        } else {
            $returnData['status'] = 0;
            $returnData['message'] = "Gagal Menambah Menu";
            $returnData['menuId'] = null;
            $returnData['menuTitle'] = null;
            $returnData['menuSlug'] = null;

        }
        return $returnData;
    }

    public function update(Request $request,$id)
    {
        $modul = Menu::find($id);
        $modul->title = $request->input('title');
        $modul->slug = $request->input('slug');
        if ($modul->update()) {
            return redirect()->back()->with('message', 'Menu telah diupdate');
        }  

    }


    public function destroy($id)
    {
        $modul = Menu::find($id);
        if ($modul->delete()) {
            return redirect()->back()->with('message', 'Menu telah dihapus');
        }  
    }

    public function reOrder(Request $request)
    {   
        $list = json_decode($request->list);
        foreach ($list as $key => $value) {
            if(property_exists($value,"id")){
                $modul = Menu::find((int)$value->id);
                $modul->order = (int)$key;
                $modul->parent_id = null;
                $modul->update();
                if (property_exists($value,"children")) {
                    foreach ($value->children as $keyChildren => $valueChildren) {
                        $modul = Menu::find((int)$valueChildren->id);
                        $modul->parent_id = (int)$value->id;
                        $modul->order = $keyChildren;
                        $modul->update();
                        if (property_exists($valueChildren,"children")) {
                            foreach ($valueChildren->children as $keySubChildren => $valueSubChildren) {
                                $modul = Menu::find((int)$valueSubChildren->id);
                                $modul->parent_id = (int)$valueChildren->id;
                                $modul->order = $keySubChildren;
                                $modul->update();
                            }
                        }
                    }
                }
                
            } 
        }
        return redirect()->back()->with('message', 'Menu telah diupdate');
    }
}

resources/views/panel/menu/create.blade.php
@extends('panel.layouts.apps')
@include('panel.menu.submenu')
@section('content')
@if(session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-line-chart"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                Menu
            </h3>
        </div>
    </div>
    <div class="kt-portlet__body">

        <form class="kt-form kt-form--label-right" id="addmenu" action="{{ route('menu.store') }}" method="POST">
            {{csrf_field()}}
            <div class="kt-portlet__body">
                <div class="form-group form-group-last">
                    <div class="alert alert-secondary" role="alert">
                        <div class="alert-icon"><i class="flaticon-add kt-font-brand"></i></div>
                        <div class="alert-text">
                            Tambah Menu
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Nama Layout</label>
                    <div class="col-8">
                        <input class="form-control" type="text" value="" id="judul_tags" name="name"
                            placeholder="Nama Layout">
                    </div>
                </div>
            </div>

            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button class="btn btn-success" type="submit">Submit</button>
                            <button type="reset" class="btn btn-secondary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
@endsection
@section('script')

@endsection

resources/views/panel/menu/edit.blade.php
@extends('panel.layouts.apps')
@include('panel.menu.submenu')
@section('content')
@if(session()->has('message'))
<div class="alert alert-error">
    {{ session()->get('message') }}
</div>
@endif
<form class="kt-form kt-form--label-right" id="editMenu" action="{{ route('menu.update',$data->id) }}" method="POST">
@method("patch")
@csrf
    <div class="kt-portlet kt-portlet--mobile">
        <input type="hidden" name="lastState" value="{{ url()->previous() }}">
        <div class="kt-portlet__body">
            <div class="form-group form-group-last">
                <div class="alert alert-secondary" role="alert">
                    <div class="alert-icon"><i class="flaticon-edit kt-font-brand"></i></div>
                    <div class="alert-text">
                        Edit Menu
                    </div>
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-2">Nama Menu</label>
                <div class="col-8">
                    <input class="form-control" type="text" value="{{ $data->name }}" id="title" name="name"
                        placeholder="Nama Menu">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-form-label col-2">Slug</label>
                <div class="col-8">
                    <input class="form-control" type="text" value="{{ $data->slug }}" id="title" name="name"
                        placeholder="Slug">
                </div>
            </div>
        </div>

        <div class="kt-portlet__foot">
            <div class="kt-form__actions">
                <div class="row">
                    <div class="col-2">
                    </div>
                    <div class="col-10">
                        <button class="btn btn-success" type="submit">Submit</button>
                        <button type="reset" class="btn btn-secondary">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@endsection
@section('script')
@endsection

resources/views/panel/menu/index.blade.php
@extends('panel.layouts.apps')
@include('panel.menu.submenu')
@section('content')
@if(session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-menu"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                Menu
            </h3>
        </div>
    </div>
    <div class="kt-portlet__body">
        <table class="table table-striped" id="t_menu">
            <thead>
                <tr>
                    <th>Menu</th>
                    <th style="text-align:center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $item)
                <tr>
                    <td width="65%">{!! $item->name !!}</td>
                    <td width="35%" style="text-align:center">
                        <a class="btn btn-success btn-icon" href="{{ route('menu.show',$item->id) }}"><i class="fas fa-external-link-alt"></i></a>
                        <a class="btn btn-primary btn-icon" href="{{ route('menu.edit',$item->id) }}"><i class="fas fa-pencil-alt"></i></a>
                        <a class="btn btn-danger deletemenu btn-icon" href="#" id-hmenu="{{ $item->id }}"><i class="fas fa-trash"></i></a>
                        <form action="{{ route('menu.destroy',$item->id) }}" style="display:none" id="destroy_{{ $item->id }}"
                            method="POST">
                            @method('delete')
                            @csrf
                        </form>
                    <td>
                </tr>
                @endforeach
            </tbody>
        </table>
        <hr>
        <div class="kt-pagination  kt-pagination--brand">
            {{ $data->links() }}
            <div class="kt-pagination__toolbar">
                <span class="pagination__desc">
                    Displaying {{ ($data->total() <= 10)?$data->total():($data->currentpage()-1)*$data->perpage()+1 }}
                    {{ ($data->currentpage()*$data->perpage() < 10)?"to ".$data->currentpage()*$data->perpage():""}} of
                    {{$data->total()}} records
                </span>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
<script>
    $(document).on('click','.newmenu',function(e){
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var valuegambar = $(this).attr('id-gambar');
        $modal.find(".modal-title").html("Tambah Menu Baru");
        $modal.find(".modal-body").html('<form action="{!! route("menu.store") !!}" method="POST">'+
            '<input type="hidden" name="_token" value="{!! csrf_token() !!}" />'+
            '<div class="form-group row">'+
                '<div class="col-12">'+
                    '<input class="form-control" type="text" id="title" name="title" placeholder="Title">'+
                    '</div>'+
                '</div>'+
            '</form>');
        $modal.find(".modal-footer").html('<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button><button type="button" class="btn btn-primary createNewMenu">OK</button>');
        $modal.modal('show');
    });
    $(document).on('click','.createNewMenu',function(e){
        $('.modal-body').children('form').trigger('submit');
    });

    $(document).on('click','.deletemenu',function(e){
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var valuemenu = $(this).attr('id-hmenu');
        $modal.find(".modal-title").html("Hapus Menu");
        $modal.find(".modal-body").html("Apakah Anda Yakin Ingin menghapus Menu ini?");
        $modal.find(".modal-footer").html('<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button><button type="button" class="btn btn-primary yeshapusmenu" valueid="'+valuemenu+'">OK</button>');
        $modal.modal('show');
    });
    $(document).on('click','.yeshapusmenu',function(e){
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var id_menu = $(this).attr('valueid');
        $('#destroy_'+id_menu).trigger('submit');
        $modal.modal('hide');
    });
</script>
@endsection

resources/views/panel/menu/show.blade.php
@extends('panel.layouts.apps')
@include('panel.menu.submenu')
@section('content')
<link rel="stylesheet" href="{!! asset('/assets/css/nestable.css') !!}">
@if(session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-menu-2"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                Menu
            </h3>
        </div>
        <div class="kt-portlet__head-toolbar">
            <a href="#" class="btn btn-brand btn-elevate menubaru">
                <i class="la la-plus"></i>
                Add New Menu
            </a>
        </div>
    </div>
    <div class="kt-portlet__body">
        <div class="row col-12">

            <div class="dd" id="nestable">
                {!! $menu !!}
            </div>
        </div>
        <hr>
        <form action="{{ route('dmenu.reorder') }}" method="POST">
            @csrf
            <textarea id="nestable-output" style="display:none" name="list"></textarea>
            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-12">
                            <button class="btn btn-success" type="submit">Update</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        
    </div>
</div>
@endsection
@push('script')
<script src="{{asset('/js/jquery.nestable.js')}}"></script>
<script>
$(document).ready(function(){
    var updateOutput = function(e){
        var list   = e.length ? e : $(e.target),
            output = list.data('output');
            $('#nestable-output').html(window.JSON.stringify(list.nestable('serialize')));
    };

    $('#nestable').nestable({
        // group: 1,
        maxDepth:10
    }).on('change', updateOutput);
    updateOutput($('#nestable').data('output', $('#nestable-output')));
});

    $(document).on('click','.menubaru',function(e){
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();
            var $modal = $('#modal-normal');
            $modal.find(".modal-title").html("Tambah Menu Baru");
            $modal.find(".modal-body").html('<div class="form-group row">'+
                '<div class="col-12">'+
                    '<input class="form-control" type="text" value="" id="title" name="title" placeholder="Title">'+
                    '</div>'+
                '</div>'+
            
            '<div class="form-group row">'+
                '<div class="col-12">'+
                    '<input class="form-control" type="text" value="" id="slug" name="slug" placeholder="Link">'+
                '</div>'+
            '</div>'+
            '<input id="layout_id" type="hidden" name="layout_id" value="{!! $data->id !!}" />');
            $modal.find(".modal-footer").html('<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button><button type="button" class="btn btn-primary createthismenu">OK</button>');
            $modal.modal('show');
       });
        $(document).on('click','.createthismenu',function(e){
            e.preventDefault();
            e.stopPropagation();
            e.stopImmediatePropagation();
            var $modal = $('#modal-normal');
            var title_ = $('#title').val();
            var layout_ = $('#layout_id').val();
            var slug_ = $('#slug').val();
            
            $.ajax({
                url:"{!! route('dmenu.store') !!}",
                type:"POST",
                data:{'title':title_,'slug':slug_,"layout_id":layout_,"_token":"{!! csrf_token() !!}"},
                success:function(e){
                    if (e.status == 1) {
                        var path = $('#nestable').children('.MenuHere');
                        path.append('<li class="dd-item kt-avatar kt-avatar--outline" data-id="'+e.menuId+'">'+
                        '<div class="dd-handle col-6">'+e.menuTitle+'</div>'+
                        '<label class="kt-avatar__upload ubahmenu" id-menu="'+e.menuId+'" data-title="'+e.menuTitle+'" data-slug="'+e.menuSlug+'" id-menu="'+e.menuId+'" data-toggle="kt-tooltip" title=" data-original-title="Ubah Menu">'+
                            '<i class="fa fa-pencil-alt"></i>'+
                            '</label>'+
                        '</li>');
                        $('#nestable').nestable().trigger('change');
                        toastr.success(e.message,"Success");
                    } else {
                        toastr.error(e.message,"Failed");
                    }
                }
            });
            $modal.modal('hide');
        });



$(document).on('click','.ubahmenu',function(e){
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
    var $modal = $('#modal-normal');
    var valuemenu = $(this).attr('id-menu');
    var title_ = $(this).attr('data-title');
    var slug_ = $(this).attr('data-slug');
    $modal.find(".modal-title").html("Ubah Menu");
    $modal.find(".modal-body").html('<form action="{!!url("panelroom/dmenu/'+valuemenu+'")!!}" method="POST" id="edit_'+valuemenu+'">'+
        '<input type="hidden" name="_method" value="patch" />'+
        '<input type="hidden" name="_token" value="{!! csrf_token() !!}" />'+
    '<div class="form-group row">'+
        '<div class="col-12">'+
            '<input class="form-control" type="text" value="'+title_+'" id="title" name="title" placeholder="Title">'+
            '</div>'+
        '</div>'+
    
    '<div class="form-group row">'+
        '<div class="col-12">'+
            '<input class="form-control" type="text" value="'+slug_+'" id="slug" name="slug" placeholder="Link">'+
            '</div>'+
        '</div>'+
        '<div class="form-group row">'+
            '<div class="col-12">'+
                '<a class="btn btn-danger hapusmenu" id-destroy="'+valuemenu+'" href="#">HAPUS</a>'+
                '</div>'+
            '</div>'+
            '</form>'+
            '<form action="{!! url("panelroom/dmenu/'+valuemenu+'") !!}" id="destroy_'+valuemenu+'" style="display:none" method="POST">'+
                '<input type="hidden" name="_method" value="delete" />'+
                '<input type="hidden" name="_token" value="{!! csrf_token() !!}" />'+
            '</form>');
        
    $modal.find(".modal-footer").html('<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button><button type="button" class="btn btn-primary submitmenu" valueid="'+valuemenu+'">OK</button>');
    $modal.modal('show');
});
$(document).on('click','.submitmenu',function(e){
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
    var $modal = $('#modal-normal');
    var id_menu = $(this).attr('valueid');
    $('#edit_'+id_menu).trigger('submit');
    $modal.modal('hide');

});
$(document).on('click','.hapusmenu',function(e){
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();
    var $modal = $('#modal-normal');
    var id_menu = $(this).attr('id-destroy');
    $('#destroy_'+id_menu).trigger('submit');
    $modal.modal('hide');
});
</script>
@endpush

resources/views/panel/menu/submenu.blade.php
@section('submenu')
<span class="kt-subheader__separator kt-hidden"></span>
<a href="{{ route('menu.index') }}" class="btn btn-label-primary btn-bold btn-sm btn-icon-h kt-margin-l-10">
    <i class="fas fa-bars"></i> Daftar Halaman Menu
</a>
<a href="{{ route('menu.create') }}" class="btn btn-label-primary btn-bold btn-sm btn-icon-h kt-margin-l-10 newmenu">
    <i class="fas fa-plus"></i> Halaman Menu Baru
</a>
@endsection