routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/hubungi', 'HomeController@showContactUs');
Route::post('/hubungi', 'HomeController@kirimPesan')->name('home.kirimPesan');

Route::get('/bukutamu/pengunjung', 'Frontend\PengunjungController@index')->name('home.pengunjung');
Route::post('/bukutamu/pengunjung/store', 'Frontend\PengunjungController@store')->name('home.pengunjung.store');
Route::get('/bukutamu/perjanjian', 'Frontend\PerjanjianController@index')->name('home.perjanjian');
Route::post('/bukutamu/perjanjian/store', 'Frontend\PerjanjianController@store')->name('home.perjanjian.store');

Route::get('/p/{slug}', 'HomeController@showPage')->name('home.showPage');

Route::get('/berita', 'HomeController@listPost')->name('home.listPost');
Route::get('/berita/{id}-{post}', 'HomeController@showPost')->name('home.showPost');

Route::get('/tag/{slug}', 'HomeController@showTags')->name('home.showTags');
Route::get('/topik/{slug}', 'HomeController@showCategories')->name('home.showCategories');

Route::get('/agenda', 'HomeController@listAgenda')->name('home.listAgenda');
Route::get('/agenda/{id}/{slug}', 'HomeController@showAgenda')->name('home.showAgenda');

Route::get('/pengumuman', 'HomeController@listPengumuman')->name('home.listPengumuman');
Route::get('/pengumuman/{id}/{slug}', 'HomeController@showPengumuman')->name('home.showPengumuman');

Route::get('/galeri', 'HomeController@listGallery')->name('home.listGallery');
Route::get('/galeri/{id}', 'HomeController@showGallery')->name('home.showGallery');

Route::get('/search', 'HomeController@showSearch');

Route::get('/faq', 'HomeController@listFaq')->name('home.listFaq');
Route::get('/layanan', 'HomeController@listLayanan')->name('home.listLayanan');


Auth::routes();
Route::group(['prefix' => 'panelroom'], function () {
    Route::get('/','DashboardController@index');
    Route::post('berita/addTags', 'BeritaController@addTags')->name('berita.addTags');

    Route::post('quickdraft', 'BeritaController@quickDraft')->name('berita.quickDraft');
    
    Route::resource('berita', 'BeritaController');
    Route::resource('kategori', 'KategoriController');
    Route::resource('tag', 'TagController');
    Route::resource('halaman', 'HalamanController');
    
    Route::get('media/modal', 'MediaController@modalshow')->name('media.modal');
    Route::get('media/modal-gallery', 'MediaController@modalShowGallery')->name('media.modal_gallery');
    Route::match(['post', 'patch'], 'media/ajaxstore', 'MediaController@ajaxStore')->name('media.ajaxstore');
    Route::resource('media', 'MediaController');
    
    Route::get('pdf/modal', 'PdfController@modalshow')->name('pdf.modal');
    Route::post('pdf/ajaxstore', 'PdfController@ajaxStore')->name('pdf.ajaxstore');
    Route::resource('pdf', 'PdfController');

    Route::resource('menu', 'LayoutController');

    Route::post('dmenu/reorder', 'MenuController@reOrder')->name('dmenu.reorder');
    Route::resource('dmenu', 'MenuController');

    Route::get('agenda/getAgenda', 'AgendaController@getAgenda');
    Route::resource('agenda', 'AgendaController');

    Route::resource('slider', 'SliderController');
    Route::resource('users', 'UsersController');
    Route::resource('pengumuman', 'PengumumanController');
    Route::resource('pesan', 'PesanController');
    Route::resource('gallery', 'GalleryController');
    Route::resource('iklan', 'IklanController');
    Route::resource('faq', 'Admin\FaqController');
    Route::delete('setting/deleted', 'SettingController@deleted')->name('setting.deleted');
    Route::resource('setting', 'SettingController');
    Route::resource('layanan', 'Admin\LayananController');
    Route::resource('linkterkait', 'Admin\LinkterkaitController');
    Route::resource('dataindek', 'Admin\DataindekController');
    Route::get('pengunjung/pdf', 'Admin\PengunjungController@pdf')->name('pengunjung.pdf');
    Route::get('pengunjung/excel', 'Admin\PengunjungController@excel')->name('pengunjung.excel');
    Route::resource('pengunjung', 'Admin\PengunjungController');
    Route::get('perjanjian/excel', 'Admin\PerjanjianController@excel')->name('perjanjian.excel');
    Route::get('perjanjian/pdf', 'Admin\PerjanjianController@pdf')->name('perjanjian.pdf');
    Route::resource('perjanjian', 'Admin\PerjanjianController');
    
});
Route::get('/panelroom', 'DashboardController@index')->name('dashboard');

// Route::get('/home', 'HomeController@index')->name('home');

app/Models/Perjanjian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Perjanjian extends Model
{
    use HasFactory;
    protected $guarded = [];
    protected $appends = ['status_name'];

    public function getStatusNameAttribute()
    {
        if($this->status == 0){
            return 'Belum Dikonfirmasi';
        }else{
            return 'Sudah Dikonfirmasi';
        }
    }
}

app/Http/Controllers/Admin/PerjanjianController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Exports\PerjanjianExport;
use App\Http\Controllers\Controller;
use App\Models\Pengunjung;
use App\Models\Perjanjian;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
class PerjanjianController extends Controller
{
    public function index()
    {
        $getModul = Perjanjian::paginate(10)->onEachSide(2);
        return view('panel.perjanjian.index',['data'=>$getModul]);
    }

    public function edit($id)
    {
        $getModul = Perjanjian::find($id);
        return view('panel.perjanjian.edit',['data'=>$getModul]);
    }

    public function update(Request $request,$id)
    {
        $getModul = Perjanjian::where('id',$id)->update([
            'komentar' => $request->komentar,
            'status' => $request->status
        ]);
        return redirect()->route('perjanjian.index')->with('message','Berhasil mengupdate perjanjian');
    }

    public function pdf()
    {
        $getModul = Perjanjian::all();
        return view('panel.perjanjian.pdf',['data'=>$getModul]);
    }

    public function excel()
    {
        return Excel::download(new PerjanjianExport, 'rekap_perjanjian.xlsx');
    }

    public function destroy($id)
    {
        $modul = Perjanjian::find($id);
        if ($modul->delete()) {
            return redirect()->back()->with('message', 'Perjanjian telah dihapus');
        }
    }
}

app/Http/Controllers/Frontend/PerjanjianController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Models\Perjanjian;
use Illuminate\Http\Request;

class PerjanjianController extends Controller
{
    public function index()
    {
        return view('home.bukutamu.perjanjian');
    }

    public function store(Request $request)
    {
        $data = $request->except('_token','kartu_identitas');
        $media = $request->file('kartu_identitas');
        $ext = $media->guessClientExtension();
        $mimeType = $media->getClientMimeType();
        $newdate = date("YmdHis");
        $origName = preg_replace('/\\.[^.\\s]{3,4}$/', '', $media->getClientOriginalName());
        $origName = str_replace(" ","-",$origName);
        $data['kartu_identitas'] = $media->storeAs("bukutamu/perjanjian", $origName . "_" . $newdate . "." . $ext, 'uploadfile');
        Perjanjian::create($data);
        return back()->with('message','Berhasil Menyimpan Data');
    }
}

resources/views/panel/perjanjian/create.blade.php
@extends('panel.layouts.apps')
@include('panel.dataindek.submenu')
@section('content')
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload.css") !!}>
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload-ui.css") !!}>
@if ($errors->any())
<div class="alert alert-danger">
    @foreach ($errors->all() as $error)
    <ul>
        <li>{{ $error }}</li>
    </ul>
    @endforeach
</div>
@endif
<form class="kt-form kt-form--label-right row" id="f_dataindek" action="{{ route('dataindek.store') }}" method="POST"
    enctype="multipart/form-data">
    {{csrf_field()}}
    <div class="col-8">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body">
                <div class="form-group form-group-last">
                    <div class="alert alert-secondary" role="alert">
                        <div class="alert-icon"><i class="flaticon-add kt-font-brand"></i></div>
                        <div class="alert-text">
                            Tambah Data Indek
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Judul Data Indek *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="" id="judul" name="judul"
                            placeholder="Judul Data Indek">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Deskripsi</label>
                    <div class="col-10">
                        <textarea rows="4" class="form-control" name="deskripsi"
                        placeholder="Deskripsi"></textarea>
                    </div>
                </div>

                
            </div>

            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button class="btn btn-success" type="submit">Submit</button>
                            <button type="reset" class="btn btn-secondary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Media
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="form-group row">
                    <input type="hidden" id="imageIdnews" value="" name="id_media">
                    <div class="col-12">
                        <div class="preview-pic"></div>
                        <hr />
                    </div>
                    <div class="col-6 text-center">
                        <span class="btn btn-success fileinput-button col-12">
                            <span class="uploadnew ">Upload</span>
                            <span class="changeupload d-none">Ganti</span>
                            <input id="fileupload" type="file" name="files">
                        </span>
                    </div>
                    <div class="col-6 text-center">
                        <a href="#" class="btn btn-primary fileinput-button pilihgambar col-12">
                            Pilih
                        </a>
                        <a href="#" class="btn btn-danger fileinput-button hapusgambar d-none col-12">
                            Hapus
                        </a>
                    </div>
                </div>
                {{-- <div class="form-group">
                    <textarea class="form-control" name="ket_gambar" id="ket_gambar" cols="30" rows="3" placeholder="Keterangan Gambar"></textarea>
                </div> --}}
            </div>
        </div>
   
    </div>
</form>
@endsection
@push('script')
<script src="{!! asset("/js/jquery-ui.js") !!}"></script>
<script src="{!! asset("/js/jquery.fileupload.js") !!}"></script>

<script>
    $(document).on('change', '#position', function(e) {
        let posVal = $('#position').val();
        switch (posVal) {
            case "1":
                $('.ordering').addClass('d-none');
                break;
            case "2":
                $('.ordering').addClass('d-none');
                break;
            default:
                $('.ordering').removeClass('d-none');
                break;
        }
    });
    $(document).ready(function() {
        $("#f_iklan").validate({
            rules: {
                title: {
                    required: !0
                },
                position: {
                    required: !0
                }
            },
            errorPlacement: function(e, r) {
                var i = r.closest(".input-group");
                i.length ? i.after(e.addClass("invalid-feedback")) : r.after(e.addClass(
                    "invalid-feedback"))
            },
            invalidHandler: function(e, r) {
                KTUtil.scrollTop();
            }
        });
    });
    $(function() {
        $('#fileupload').fileupload({
            url: '{!! route("media.ajaxstore") !!}',
            dataType: 'json',
            done: function(e, data) {
                var dataRes = data.result;
                if (dataRes.status == 1) {
                    $('.uploadnew').addClass('d-none');
                    $('.changeupload').removeClass('d-none');
                    $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + dataRes
                        .path + '" />');
                    $('fileinput-button').html('Ganti Gambar');
                    $('#imageIdnews').val(dataRes.imageId);
                    $('.pilihgambar').addClass('d-none');
                    $('.hapusgambar').removeClass('d-none');
                    toastr.success(dataRes.message, "Success");
                } else {
                    toastr.error(dataRes.message, "Failed");
                }
            }
        });
    });
    $(document).on('click', '.pilihgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        $modal.find(".modal-title").html("Pilih Gambar");
        $modal.find(".modal-body").html("");
        $.ajax({
            url: "{{ route('media.modal') }}",
            type: "GET",
            data: {},
            success: function(e) {
                $modal.find(".modal-body").html(e);
            }
        });
        $modal.find(".modal-footer").html('');
        $modal.modal('show');
    });
    $(document).on('click', '.choosepicture', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        var id_gambar = $(this).attr('id-gambar');
        var path_gambar = $(this).attr('path-gambar');
        $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + path_gambar + '" />');
        $('#imageIdnews').val(id_gambar);
        $('.pilihgambar').addClass('d-none');
        $('.hapusgambar').removeClass('d-none');
        $modal.modal('hide');
    });
    $(document).on('click', '.hapusgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        $('.preview-pic').html('');
        $('#imageIdnews').val('');
        $('.pilihgambar').removeClass('d-none');
        $('.hapusgambar').addClass('d-none');
        $('.uploadnew').removeClass('d-none');
        $('.changeupload').addClass('d-none');
    });
</script>
@endpush

resources/views/panel/perjanjian/edit.blade.php
@extends('panel.layouts.apps')
@section('content')
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload.css") !!}>
<link rel="stylesheet" href={!! asset("jsUpload/css/jquery.fileupload-ui.css") !!}>
@if ($errors->any())
<div class="alert alert-danger">
    @foreach ($errors->all() as $error)
    <ul>
        <li>{{ $error }}</li>
    </ul>
    @endforeach
</div>
@endif
<form class="kt-form kt-form--label-right row" id="f_perjanjian" action="{{ route('perjanjian.update',$data->id) }}" method="POST"
    enctype="multipart/form-data">
    {{csrf_field()}}
    @method('patch')
    <div class="col-8">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body">
                <div class="form-group form-group-last">
                    <div class="alert alert-secondary" role="alert">
                        <div class="alert-icon"><i class="flaticon-add kt-font-brand"></i></div>
                        <div class="alert-text">
                            Konfirmasi Perjanjian
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Nama *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="{{ $data->nama }}" id="judul" name="judul"
                            placeholder="Judul Data Indeks" readonly disabled>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Tanggal *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="{{ $data->tanggal }}" id="judul" name="judul"
                            placeholder="Judul Data Indeks" readonly disabled>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Jam *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="{{ $data->jam }}" id="judul" name="judul"
                            placeholder="Judul Data Indeks" readonly disabled>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Tujuan *</label>
                    <div class="col-10">
                        <input class="form-control" type="text" value="{{ $data->tujuan }}" id="judul" name="judul"
                            placeholder="Judul Data Indeks" readonly disabled>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Alamat</label>
                    <div class="col-10">
                        <textarea rows="4" class="form-control" name="deskripsi"
                        placeholder="Deskripsi" readonly disabled>{{ $data->alamat }}</textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Komentar</label>
                    <div class="col-10">
                        <textarea rows="4" class="form-control" name="komentar"
                        placeholder="Komentar"></textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-form-label col-2">Status</label>
                    <div class="col-10">
                       <select name="status" id="" class="form-control">
                        <option value="0">Belum Dikonfirmasi</option>
                        <option value="1">Konfirmasi</option>
                       </select>
                    </div>
                </div>
                
            </div>

            <div class="kt-portlet__foot">
                <div class="kt-form__actions">
                    <div class="row">
                        <div class="col-2">
                        </div>
                        <div class="col-10">
                            <button class="btn btn-success" type="submit">Submit</button>
                            <button type="reset" class="btn btn-secondary">Cancel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-4">
        <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Kartu Identitas
                    </h3>
                </div>
            </div>
            <div class="kt-portlet__body">
                <div class="form-group row">
                    <div class="col-12">
                        <div class="preview-pic">
                            <img src="{{ asset('files/'. $data->kartu_identitas) }}" alt="" width="100%">  
                        </div>
                        <hr />
                    </div>
                </div>
                {{-- <div class="form-group">
                    <textarea class="form-control" name="ket_gambar" id="ket_gambar" cols="30" rows="3" placeholder="Keterangan Gambar"></textarea>
                </div> --}}
            </div>
        </div>
   
    </div>
</form>
@endsection
@push('script')
<script src="{!! asset("/js/jquery-ui.js") !!}"></script>
<script src="{!! asset("/js/jquery.fileupload.js") !!}"></script>

<script>
    $(document).on('change', '#position', function(e) {
        let posVal = $('#position').val();
        switch (posVal) {
            case "1":
                $('.ordering').addClass('d-none');
                break;
            case "2":
                $('.ordering').addClass('d-none');
                break;
            default:
                $('.ordering').removeClass('d-none');
                break;
        }
    });
    $(document).ready(function() {
        $("#f_iklan").validate({
            rules: {
                title: {
                    required: !0
                },
                position: {
                    required: !0
                }
            },
            errorPlacement: function(e, r) {
                var i = r.closest(".input-group");
                i.length ? i.after(e.addClass("invalid-feedback")) : r.after(e.addClass(
                    "invalid-feedback"))
            },
            invalidHandler: function(e, r) {
                KTUtil.scrollTop();
            }
        });
    });
    $(function() {
        $('#fileupload').fileupload({
            url: '{!! route("media.ajaxstore") !!}',
            dataType: 'json',
            done: function(e, data) {
                var dataRes = data.result;
                if (dataRes.status == 1) {
                    $('.uploadnew').addClass('d-none');
                    $('.changeupload').removeClass('d-none');
                    $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + dataRes
                        .path + '" />');
                    $('fileinput-button').html('Ganti Gambar');
                    $('#imageIdnews').val(dataRes.imageId);
                    $('.pilihgambar').addClass('d-none');
                    $('.hapusgambar').removeClass('d-none');
                    toastr.success(dataRes.message, "Success");
                } else {
                    toastr.error(dataRes.message, "Failed");
                }
            }
        });
    });
    $(document).on('click', '.pilihgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        $modal.find(".modal-title").html("Pilih Gambar");
        $modal.find(".modal-body").html("");
        $.ajax({
            url: "{{ route('media.modal') }}",
            type: "GET",
            data: {},
            success: function(e) {
                $modal.find(".modal-body").html(e);
            }
        });
        $modal.find(".modal-footer").html('');
        $modal.modal('show');
    });
    $(document).on('click', '.choosepicture', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-full');
        var id_gambar = $(this).attr('id-gambar');
        var path_gambar = $(this).attr('path-gambar');
        $('.preview-pic').html('<img width="100%" src="{!! url("files") !!}/' + path_gambar + '" />');
        $('#imageIdnews').val(id_gambar);
        $('.pilihgambar').addClass('d-none');
        $('.hapusgambar').removeClass('d-none');
        $modal.modal('hide');
    });
    $(document).on('click', '.hapusgambar', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        $('.preview-pic').html('');
        $('#imageIdnews').val('');
        $('.pilihgambar').removeClass('d-none');
        $('.hapusgambar').addClass('d-none');
        $('.uploadnew').removeClass('d-none');
        $('.changeupload').addClass('d-none');
    });
</script>
@endpush

resources/views/panel/perjanjian/excel.blade.php
<table class="">
    <thead>
        <tr>
            <th>Nama</th>
            <th>Alamat</th>
            <th>Tanggal</th>
            <th>Jam</th>
            <th>Tujuan</th>
            <th>Komentar</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($data as $item)
        <tr>
            <td>{{ $item->nama }}</td>
            <td>{{ $item->alamat }}</td>
            <td>{{ $item->tanggal }}</td>
            <td>{{ $item->jam }}</td>
            <td>{{ $item->tujuan }}</td>
            <td>{{ $item->komentar ?? '-' }}</td>
        </tr>
        @endforeach

    </tbody>
</table>

resources/views/panel/perjanjian/index.blade.php
@extends('panel.layouts.apps')
@section('content')
@if(session()->has('message'))
<div class="alert alert-success">
    {{ session()->get('message') }}
</div>
@endif
<div class="kt-portlet kt-portlet--mobile">
    <div class="kt-portlet__head kt-portlet__head--lg">
        <div class="kt-portlet__head-label">
            <span class="kt-portlet__head-icon">
                <i class="kt-font-brand flaticon2-menu-2"></i>
            </span>
            <h3 class="kt-portlet__head-title">
                List Data Perjanjian
            </h3>
        </div>
        <div class="text-right d-flex align-items-center">
            <a href="{{ route('perjanjian.pdf') }}" class="btn btn-warning btn-sm text-white mr-3">Export Pdf</a>
            <a href="{{ route('perjanjian.excel') }}" class="btn btn-success btn-sm">Export Excel</a>
        </div>
    </div>
    <div class="kt-portlet__body">
        <table class="table table-striped" id="t_menu">
            <thead>
                <tr>
                    <th>Nama</th>
                    <th>Kartu Identitas</th>
                    <th>Alamat</th>
                    <th>Tanggal</th>
                    <th>Jam</th>
                    <th>Tujuan</th>
                    <th>Status</th>
                    <th>Komentar</th>
                    <th style="text-align:center">Actions</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $item)
                <tr>
                    <td>{{ $item->nama }}</td>
                    <td><img src="{{ asset('files/'. $item->kartu_identitas) }}" alt="" width="200"></td>
                    <td>{{ $item->alamat }}</td>
                    <td>{{ $item->tanggal }}</td>
                    <td>{{ $item->jam }}</td>
                    <td>{{ $item->tujuan }}</td>
                    <td>{{ $item->status_name }}</td>
                    <td>{{ $item->komentar }}</td>
                    <td width="20%" style="text-align:center">
                        <a class="btn btn-primary btn-icon" href="{{ route('perjanjian.edit',$item->id) }}"><i
                                class="fas fa-pencil-alt"></i></a>
                        <button type="button" class="btn btn-danger destroy deleteperjanjian btn-icon" id-perjanjian="{{ $item->id }}"><i
                                class="fas fa-trash"></i></button>
                        <form action="{{ route('perjanjian.destroy',$item->id) }}" style="display:none"
                            id="destroy_{{ $item->id }}" method="POST">
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
                @endforeach

            </tbody>
        </table>
        <div class="kt-pagination  kt-pagination--brand">
            {{ $data->links() }}
            <div class="kt-pagination__toolbar">
                <span class="pagination__desc">
                    Displaying {{ ($data->total() <= 10)?$data->total():($data->currentpage()-1)*$data->perpage()+1 }}
                    {{ ($data->currentpage()*$data->perpage() < 10)?"to ".$data->currentpage()*$data->perpage():""}} of
                    {{$data->total()}} records
                </span>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script>
    $(document).on('click', '.deleteperjanjian', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var valueperjanjian = $(this).attr('id-perjanjian');
        $modal.find(".modal-title").html("Hapus Slide");
        $modal.find(".modal-body").html("Apakah Anda Yakin Ingin menghapus perjanjian ini?");
        $modal.find(".modal-footer").html(
            '<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button><button type="button" class="btn btn-primary yeshapuperjanjian" valueid="' +
            valueperjanjian + '">OK</button>');
        $modal.modal('show');
    });
    $(document).on('click', '.yeshapuperjanjian', function(e) {
        e.preventDefault();
        e.stopPropagation();
        e.stopImmediatePropagation();
        var $modal = $('#modal-normal');
        var id_perjanjian = $(this).attr('valueid');
        $('#destroy_' + id_perjanjian).trigger('submit');
        $modal.modal('hide');
    });
</script>
@endpush

resources/views/panel/perjanjian/submenu.blade.php
@section('submenu')
<span class="kt-subheader__separator kt-hidden"></span>
<a href="{{ route('dataindek.create') }}" class="btn btn-label-primary btn-bold btn-sm btn-icon-h kt-margin-l-10">
    <i class="fas fa-plus"></i> Tambah Data Indeks
</a>
@endsection